export interface ApplicationInfo {
    id: number | null;
    applicant_id: number | null;
    job_posting_id: number | null;
    first_name: string | null,
    last_name: string | null,
    email: string | null,
    phone_number: string | null,
    address: string | null,
    date_of_birth: string | null,
    gender: string | null,
    nationality: string | null,
    work_experience: string | null,
    education_history: string | null,
    skills: string | null,
    languages_spoken: string | null,
    references: string | null,
    cover_letter: string | null,
    resume: string | null,
    additional_documents: string | null,
    application_status: string | null,
    application_date: string | null,
    notes: string | null,
}