<template>
  <SharedUiCustomTable :show-footer-in-head="false" :headers="headers" :items="reports" :loading="loading">
    <template v-slot:item.actions="{ item }">
      <v-icon class="ml-2" color="primary" dense @click="$emit('view', item)">mdi-eye</v-icon>
      <v-icon class="ml-2" color="primary" dense @click="$emit('edit', item)">mdi-pencil</v-icon>
      <v-icon class="ml-2" color="red" dense @click="$emit('delete', item)">mdi-delete</v-icon>
    </template>
  </SharedUiCustomTable>
</template>

<script lang="ts" setup>
import { defineProps, defineEmits } from 'vue';
import { useReportsStore } from '@/stores/maintenance/reportsStore';

const emit = defineEmits(['view', 'edit', 'delete']);

const reportsStore = useReportsStore();
const reports = computed(() => reportsStore.reports);
const loading = computed(() => reportsStore.loading);

const headers = [
  { title: 'Report ID', key: 'id' },
  { title: 'Report Name', key: 'name' },
  { title: 'Report Type', key: 'type' },
  { title: 'Generated Date', key: 'generated_date' },
  { title: 'Generated By', key: 'generated_by' },
  { title: 'File', key: 'file', sortable: false },
  { title: 'Actions', key: 'actions', sortable: false },
];
</script>